/*
-- Query: select * from tradinginfo
LIMIT 0, 1000

-- Date: 2016-03-09 19:41
*/

CREATE TABLE `tradinginfo` (
  `TRADING_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '交易ID',
  `TRADING_GOODS_ID` int(11) NOT NULL COMMENT '交易商品ID',
  `TRADING_USER_ID` int(11) NOT NULL COMMENT '交易买家ID',
  `TRADING_NUMBER` int(11) DEFAULT NULL COMMENT '交易数量',
  PRIMARY KEY (`TRADING_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;


INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (1,4,1,1);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (2,7,2,3);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (3,3,4,1);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (4,2,5,1);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (5,2,3,5);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (6,8,4,2);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (7,9,4,3);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (8,10,5,4);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (9,11,1,5);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (10,9,1,6);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (11,9,2,3);
INSERT INTO `tradinginfo` (`TRADING_ID`,`TRADING_GOODS_ID`,`TRADING_USER_ID`,`TRADING_NUMBER`) VALUES (12,9,3,2);
